// Generated by Unloop
// Office Thermostat

slint::include_modules!();

// Export function for WASM initialization
#[cfg(target_arch = "wasm32")]
use wasm_bindgen::prelude::*;

#[cfg(target_arch = "wasm32")]
#[wasm_bindgen]
pub fn init() -> Result<(), wasm_bindgen::JsValue> {
    console_error_panic_hook::set_once();
    
    let app = App::new().map_err(|e| wasm_bindgen::JsValue::from_str(&e.to_string()))?;
    
    // TODO: Wire up callbacks to actual hardware/logic
    app.on_quick_cool_clicked(|| {
        println!("quick_cool clicked");
    });
    
    app.on_schedule_clicked(|| {
        println!("schedule clicked");
    });
    

    
    app.run().map_err(|e| wasm_bindgen::JsValue::from_str(&e.to_string()))?;
    Ok(())
}

// For native builds, provide a main function
#[cfg(not(target_arch = "wasm32"))]
pub fn main() -> Result<(), slint::PlatformError> {
    let app = App::new()?;
    
    // TODO: Wire up callbacks to actual hardware/logic
    app.on_quick_cool_clicked(|| {
        println!("quick_cool clicked");
    });
    
    app.on_schedule_clicked(|| {
        println!("schedule clicked");
    });
    

    
    app.run()
}
